### ISSUE TITLE
Failed to grant owner

### ISSUE THREAD

**Issue by sm2x** [nvonahsen/jitsi-token-moderation-plugin#6]
Ubuntu 18.04LTS
Lua5.1/Luarocks
Prosody Trunk 1249
Jitsi Meet Latest stable as of today

If I enable token_moderation, I get the above error on jicofo log followed by this
<type='error'><error type='modify'><not-acceptable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error>

**Comment by davidroberthoare** [comment]
I'm seeing the same thing. error output:
`Jicofo 2020-05-16 19:39:13.958 INFO: [28] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@50e027a0 member=ChatMember[another_new_room@conference.jitsi.gumzo.com/22cc1470, jid: null]@848152460]
Jicofo 2020-05-16 19:39:13.959 SEVERE: [28] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Failed to grant owner status to 22cc1470-7792-4bc8-995a-a2177e494f8e@jitsi.gumzo.com/voXUGo0x
java.lang.RuntimeException: Failed to grant owner: <iq to='focus@auth.jitsi.gumzo.com/focus2227177115901983' from='another_new_room@conference.jitsi.gumzo.com' id='ftfym-4409' type='error'><error type='modify'><not-acceptable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.grantOwnership(ChatRoomImpl.java:808)
	at org.jitsi.jicofo.ChatRoomRoleAndPresence.grantOwner(ChatRoomRoleAndPresence.java:332)
	at org.jitsi.jicofo.ChatRoomRoleAndPresence.electNewOwner(ChatRoomRoleAndPresence.java:247)
	at org.jitsi.jicofo.ChatRoomRoleAndPresence.memberPresenceChanged(ChatRoomRoleAndPresence.java:159)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.lambda$notifyMemberJoined$1(ChatRoomImpl.java:917)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.notifyMemberJoined(ChatRoomImpl.java:917)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.processOtherPresence(ChatRoomImpl.java:1206)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.processPresence(ChatRoomImpl.java:1255)
	at org.jivesoftware.smackx.muc.MultiUserChat$3.processStanza(MultiUserChat.java:251)
	at org.jivesoftware.smack.AbstractXMPPConnection$6.run(AbstractXMPPConnection.java:1263)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by sm2x** [comment]
Its was a case of unsupported Prosody version, solved by redoing Lua, Prosody, and Jitsi-meet-token using this guide https://github.com/christiancuri/Docs

**Comment by davidroberthoare** [comment]
> Its was a case of unsupported Prosody version, solved by redoing Lua, Prosody, and Jitsi-meet-token using this guide https://github.com/christiancuri/Docs

Hi :-) that doc you referenced has full installation instructions... what specific aspects did you have to adjust to get this plugin working again without errors? The rest of my setup is working perfectly, but for this error message, and I don't want to mess with anything I don't have to... Thanks!

**Comment by sm2x** [comment]
it was the Prosody version, I have installed the latest stable version Prosody 0.11
in reinstalling this version, you also have to reinstall Lua5.2, Luarocks and its Rocks, jitsi-meet-token
assuming you already have a working system then, uninstall all packages related to Prosody,
that's when the referred doc comes in, follow exactly the Lua5.2 and Prosody portion.
